---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      balanced-apt:
        allow_unstable: true
      postgresql:
        version: 9.3
      sentry:
        enabled: false

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
    - recipe[role-fical]
